### ISSUE TITLE
训练的图像分辨率问题

### ISSUE THREAD

**Issue by chenqi13814529300** [yzslab/gaussian-splatting-lightning#48]
python main.py fit  --config configs/appearance_embedding_renderer/view_dependent-estimated_depth_reg.yaml  --data.path E:\Data\gspl\art  --data.parser.appearance_groups appearance_image_dedicated   --data.parser.down_sample_factor 4  --data.train_max_num_images_to_cache 1024

报错：FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Data\\gspl\\art\\images_4\\0.jpg'

这下采样数据必须在做colmap前准备好吗，好像有点麻烦

**Comment by yzslab** [comment]
You have to resize your images manually before training.
Try [utils/image_downsample.py](https://github.com/yzslab/gaussian-splatting-lightning/blob/main/utils/image_downsample.py), but I have not tested whether it works on Windows.

**Comment by yzslab** [comment]
You need to remove the upper case extension names here, since the filenames on Windows are case-insensitive:
https://github.com/yzslab/gaussian-splatting-lightning/blob/771222c3c5fb3aac8940658bb248d3837f307349/utils/image_downsample.py#L43-L50

**Comment by yzslab** [comment]
> RuntimeError: The size of tensor a (5328) must match the size of tensor b (1600) at non-singleton dimension 2

The camera intrinsics loaded from colmap sparse model do not match your images. You must specify `--data.parser.down_sample_factor` if you have down-sized your images. Please note that `--data.parser.down_sample_factor` only accepts an integer. Using `1600` directly is impossible for your colmap model because `5328 / 1600` can not produce an integer.

A simpler way is resizing using colmap: `colmap image_undistorter --image_path IMAGE_PATH --input_path SPARSE_MODEL_PATH --output_path OUTPUT_PATH --max_image_size 1600` ([here is an example](https://github.com/yzslab/gaussian-splatting-lightning/blob/771222c3c5fb3aac8940658bb248d3837f307349/utils/meganerf2colmap.py#L213-L221)). Both the resized sparse model and images will be saved to `OUTPUT_PATH`. Then use `OUTPUT_PATH` as the value of `--data.path`.

**Comment by chenqi13814529300** [comment]
好的，谢谢您的回答。epoch=6-step=6999.ckpt 这些文件 如何用SIBR这些打开，或者是否可以转换为通用格式ply

**Comment by yzslab** [comment]
> 好的，谢谢您的回答。epoch=6-step=6999.ckpt 这些文件 如何用SIBR这些打开，或者是否可以转换为通用格式ply

Already mentioned in the 2.1 section of README: https://github.com/yzslab/gaussian-splatting-lightning?tab=readme-ov-file#21-basic-command

An extra operation is required if you are using the appearance model, please refer to `Remove the dependence on MLP when rendering` of the section [2.12.](https://github.com/yzslab/gaussian-splatting-lightning?tab=readme-ov-file#212-appearance-model)

**Comment by chenqi13814529300** [comment]
谢谢您的回答，我可以正常测试降采样+外观+深度进行训练了，得到的结果看起来还是不错的。
![image](https://github.com/user-attachments/assets/48588ab2-7065-4252-8d0d-3db873a418f6)
这两个有啥区别，应用场景呢。我确实挺希望您有一个yaml文件的场景推荐的。然后再给一些命令行，我相信不会花费您多少时间的。
加油更新，这个仓库真的很好。

**Comment by yzslab** [comment]
> 这两个有啥区别

The "hard depth" will treat all Gaussian as completely opaque when rendering the depth map, which is better at removing floaters/artifacts, but may lower the metrics for some scenes.
https://github.com/yzslab/gaussian-splatting-lightning/blob/771222c3c5fb3aac8940658bb248d3837f307349/internal/renderers/gsplat_renderer.py#L172

It is difficult to tell you which one is more favorable for which scenes. You need to have your own experiments.

**Comment by chenqi13814529300** [comment]
非常感谢，接下来我会多做实验。
