### ISSUE TITLE
Change num workers for Dataloader

### ISSUE THREAD

**Issue by alpergel** [yzslab/gaussian-splatting-lightning#80]
Hi I was wondering if there is an easy way to change num workers and batch size for larger machines? I have it running on a VM in azure, so its bottlenecked by numworkers right now.

**Comment by yzslab** [comment]
Hi, the batch size can not be changed currently. You can increase the
number of threads for loading images files by ‘--data.num_workers N’.
Please note that this option only speedup image loading, and all of the
images will be loaded into CPU memory by default. So the training speed
will not be affected by this option.
If you have enough GPU memory you can try to put the  images into GPU
memory, it may speedup a little bit: ‘--data.image_on_cpu false’.

You may noticed a warning message about the value of num_worker. Simply
ignore it because this repo use a customized multiple threading loader
instead of the one provided by DataLoader.

**Comment by alpergel** [comment]
Perfect! Thank you!
